# 
# Synthesis run script generated by Vivado
# 

set_param memdata.disableAnnotatedBMM 1
set_param memdata.disableBRAMInitStrings 1
set_param memdata.ignoreEmbeddedBMMProperties 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.cache/wt [current_project]
set_property parent.project_path /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/bm_trans_bram.bd
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_axi_bram_ctrl_0_0/bm_trans_bram_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_axi_bram_ctrl_1_0/bm_trans_bram_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_axi_cdma_0_0/bm_trans_bram_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_axi_cdma_0_0/bm_trans_bram_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_xbar_0/bm_trans_bram_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_blk_mem_gen_0_0/bm_trans_bram_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_processing_system7_0_0/bm_trans_bram_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_xbar_1/bm_trans_bram_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_0/bm_trans_bram_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_1/bm_trans_bram_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_auto_us_0/bm_trans_bram_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_auto_us_0/bm_trans_bram_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_2/bm_trans_bram_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_3/bm_trans_bram_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/bm_trans_bram_ooc.xdc]
set_property is_locked true [get_files /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/bm_trans_bram.bd]

read_verilog -library xil_defaultlib /home/einsamer-wolf/Vivado/part/bm_trans_v2/proj/proj.srcs/sources_1/bd/bm_trans_bram/hdl/bm_trans_bram_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top bm_trans_bram_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef bm_trans_bram_wrapper.dcp
catch { report_utilization -file bm_trans_bram_wrapper_utilization_synth.rpt -pb bm_trans_bram_wrapper_utilization_synth.pb }
