# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bm_trans_bram/bm_trans_bram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram || ORIG_REF_NAME==bm_trans_bram}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_axi_bram_ctrl_0_0/bm_trans_bram_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==bm_trans_bram_axi_bram_ctrl_0_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_axi_bram_ctrl_1_0/bm_trans_bram_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_axi_bram_ctrl_1_0 || ORIG_REF_NAME==bm_trans_bram_axi_bram_ctrl_1_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_axi_cdma_0_0/bm_trans_bram_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_axi_cdma_0_0 || ORIG_REF_NAME==bm_trans_bram_axi_cdma_0_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_axi_mem_intercon_0/bm_trans_bram_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_axi_mem_intercon_0 || ORIG_REF_NAME==bm_trans_bram_axi_mem_intercon_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_xbar_0/bm_trans_bram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_xbar_0 || ORIG_REF_NAME==bm_trans_bram_xbar_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_axi_mem_intercon_1_0/bm_trans_bram_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_axi_mem_intercon_1_0 || ORIG_REF_NAME==bm_trans_bram_axi_mem_intercon_1_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_blk_mem_gen_0_0/bm_trans_bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bm_trans_bram_blk_mem_gen_0_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_processing_system7_0_0/bm_trans_bram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_processing_system7_0_0 || ORIG_REF_NAME==bm_trans_bram_processing_system7_0_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_processing_system7_0_axi_periph_0/bm_trans_bram_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==bm_trans_bram_processing_system7_0_axi_periph_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_xbar_1/bm_trans_bram_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_xbar_1 || ORIG_REF_NAME==bm_trans_bram_xbar_1}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==bm_trans_bram_rst_processing_system7_0_100M_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_0/bm_trans_bram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_auto_pc_0 || ORIG_REF_NAME==bm_trans_bram_auto_pc_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_1/bm_trans_bram_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_auto_pc_1 || ORIG_REF_NAME==bm_trans_bram_auto_pc_1}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_auto_us_0/bm_trans_bram_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_auto_us_0 || ORIG_REF_NAME==bm_trans_bram_auto_us_0}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_2/bm_trans_bram_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_auto_pc_2 || ORIG_REF_NAME==bm_trans_bram_auto_pc_2}]

# IP: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_3/bm_trans_bram_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_auto_pc_3 || ORIG_REF_NAME==bm_trans_bram_auto_pc_3}]

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_axi_bram_ctrl_0_0/bm_trans_bram_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_axi_bram_ctrl_1_0/bm_trans_bram_axi_bram_ctrl_1_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_axi_cdma_0_0/bm_trans_bram_axi_cdma_0_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_axi_cdma_0_0/bm_trans_bram_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bm_trans_bram_axi_cdma_0_0 || ORIG_REF_NAME==bm_trans_bram_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_xbar_0/bm_trans_bram_xbar_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_blk_mem_gen_0_0/bm_trans_bram_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_processing_system7_0_0/bm_trans_bram_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bm_trans_bram_processing_system7_0_0 || ORIG_REF_NAME==bm_trans_bram_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_xbar_1/bm_trans_bram_xbar_1_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==bm_trans_bram_rst_processing_system7_0_100M_0}]

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bm_trans_bram_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==bm_trans_bram_rst_processing_system7_0_100M_0}]

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_rst_processing_system7_0_100M_0/bm_trans_bram_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_0/bm_trans_bram_auto_pc_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_1/bm_trans_bram_auto_pc_1_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_auto_us_0/bm_trans_bram_auto_us_0_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_auto_us_0/bm_trans_bram_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bm_trans_bram_auto_us_0 || ORIG_REF_NAME==bm_trans_bram_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_2/bm_trans_bram_auto_pc_2_ooc.xdc

# XDC: bd/bm_trans_bram/ip/bm_trans_bram_auto_pc_3/bm_trans_bram_auto_pc_3_ooc.xdc

# XDC: bd/bm_trans_bram/bm_trans_bram_ooc.xdc
